/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Options for a wesc build. Mirrors the CLI flags. */
export interface BuildOptions {
  /** Entry point file paths. The first entry is the host document. */
  input: Array<string>;
  /** Optional path to write the bundled CSS file. */
  outcss?: string;
  /** Optional path to write the bundled JS file. */
  outjs?: string;
  /** Minify generated JS/CSS assets where supported. Defaults to `false`. */
  minify?: boolean;
}
/**
 * Build the entry points and return the full HTML output as a `Buffer`.
 *
 * Synchronous: blocks the calling thread until the build completes. Fine for
 * build scripts; prefer [`build_async`] on a request-serving hot path.
 */
export declare function build(options: BuildOptions): Buffer;
/**
 * Build off the JS thread and resolve with the full output as a `Buffer`.
 *
 * Runs on libuv's thread pool, so it never blocks the event loop — the right
 * choice for a server that builds per request.
 */
export declare function buildAsync(options: BuildOptions): Promise<Buffer>;
/**
 * Stream the build to a callback, chunk by chunk, for low-memory output.
 *
 * The callback is invoked as `(chunk: Buffer | null)` — each chunk as it is
 * produced, then once with `null` to signal the end of the stream. Runs on a
 * background thread, so the event loop stays free while chunks flow.
 *
 * ```js
 * build_stream({ input: ['./index.html'] }, (chunk) => {
 *   if (chunk === null) res.end();
 *   else res.write(chunk);
 * });
 * ```
 */
export declare function buildStream(
  options: BuildOptions,
  callback: (arg: Buffer | undefined | null) => any,
): void;
