#!/usr/bin/env node
import { cp, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { build } from 'wesc';

import { highlightHtml } from './highlight.ts';

// Build entrypoint invoked by Wrangler's `[build] command` (and `npm run
// build`). This is the dogfooding: we run the `wesc` npm package on the host to
// expand the single-file `.html` components in `web/` into HTML and bundle the
// shared CSS/JS, then write a small ES module (`dist/generated.js`) that the
// Worker imports — Wrangler inlines it into the Worker bundle at deploy time.

const scriptsDir = dirname(fileURLToPath(import.meta.url));
const siteRoot = resolve(scriptsDir, '..');
const webRoot = join(siteRoot, 'web');
const distDir = join(siteRoot, 'dist');
const mirroredWeb = join(distDir, 'web');

// Page sources that get Shiki highlighting before they're rendered; the rest of
// web/ is used as-is. Keep this in sync with the Worker's routes.
const PAGES = ['home.html', 'docs.html', 'not-found.html'] as const;

const started = performance.now();
console.log('⏳ building wesc site');

await mkdir(distDir, { recursive: true });
await rm(mirroredWeb, { recursive: true, force: true });
await rm(join(distDir, '.wesc'), { recursive: true, force: true });

// Mirror web/ and Shiki-highlight the page sources in the copy, so wesc expands
// the highlighted markup. Components are used verbatim.
await cp(webRoot, mirroredWeb, { recursive: true });
for (const page of PAGES) {
  const file = join(mirroredWeb, 'pages', page);
  const html = await readFile(file, 'utf8');
  const highlighted = await highlightHtml(html);
  if (highlighted !== html) await writeFile(file, highlighted);
}

// Expand each page to HTML. wesc resolves the component definitions relative to
// the page file in the mirror; no assets requested, just the markup.
const pages: Record<string, string> = {};
for (const page of PAGES) {
  const { html } = build({ input: [join(mirroredWeb, 'pages', page)] });
  pages[page] = html.toString('utf8');
}

// Bundle the shared CSS + JS once. Empty `outcss`/`outjs` keep the bundles in
// memory only (no files written); rolldown's scratch lands under dist/.
const assets = build({
  input: [join(mirroredWeb, 'assets.html')],
  cwd: distDir,
  outcss: '',
  outjs: '',
  minify: true,
});

const generated = `// @generated by scripts/build-site.ts — do not edit.

export const HOME_HTML = ${JSON.stringify(pages['home.html'])};
export const DOCS_HTML = ${JSON.stringify(pages['docs.html'])};
export const NOT_FOUND_HTML = ${JSON.stringify(pages['not-found.html'])};
export const STYLES_CSS = ${JSON.stringify(assets.css ?? '')};
export const SCRIPTS_JS = ${JSON.stringify(assets.js ?? '')};
`;

await writeFile(join(distDir, 'generated.js'), generated);

console.log(`✅ built wesc site in ${Math.round(performance.now() - started)} ms`);
