//! Build-time dogfooding of wesc.
//!
//! wesc can't run inside the Worker (it depends on rolldown, which doesn't
//! target wasm32-unknown-unknown), so we run it here, on the host, as a build
//! dependency. It does two things:
//!
//! 1. Builds the shared `styles.css` + `scripts.js` bundles once from
//!    `web/assets.html` (which references every component).
//! 2. Expands each page in `web/pages/` to HTML, applies build-time Shiki
//!    syntax highlighting, and records chunks of the final HTML for streaming.
//!
//! The results are written to `OUT_DIR` and stitched into a small generated
//! Rust module (`generated.rs`) that `src/lib.rs` includes. The Worker then
//! streams the pre-expanded/highlighted HTML and serves the bundles from their
//! own routes.

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use wesc::{build, BuildOptions};

/// (route id, source file under web/pages, Rust const name).
const PAGES: &[(&str, &str, &str)] = &[
    ("home", "home.html", "HOME"),
    ("docs", "docs.html", "DOCS"),
    ("not_found", "not-found.html", "NOT_FOUND"),
];

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let web = manifest.join("web");
    let out = PathBuf::from(std::env::var("OUT_DIR").unwrap());

    // Rebuild whenever any component or page source changes.
    println!("cargo:rerun-if-changed={}", web.display());

    // wesc runs from OUT_DIR: its `.wesc` scratch tree and the emitted bundles
    // land there, while entry paths are absolute so the source tree is untouched
    // (the same pattern the rust-server example uses).
    let cwd = out.to_string_lossy().into_owned();

    // 1. Shared CSS/JS bundles. The expanded HTML from this entry is discarded.
    build(
        BuildOptions {
            input: vec![abs(&web.join("assets.html"))],
            source: None,
            outcss: Some("styles.css".to_string()),
            outjs: Some("scripts.js".to_string()),
            cwd: Some(cwd.clone()),
            minify: true,
        },
        &mut |_chunk: &[u8]| {},
    );

    // 2. Per-page HTML, capturing wesc's streamed chunk boundaries.
    let mut generated = String::new();
    generated.push_str("// @generated by build.rs via wesc — do not edit.\n");
    generated.push_str(
        "/// A pre-expanded page: its final HTML plus byte lengths used by the\n\
         /// Worker to stream it in bounded chunks.\n\
         pub struct Page {\n    pub html: &'static [u8],\n    pub chunks: &'static [usize],\n}\n\n",
    );

    let mut page_outputs: Vec<(&str, String, PathBuf)> = Vec::new();

    for (id, file, const_name) in PAGES {
        let entry = web.join("pages").join(file);
        let mut html: Vec<u8> = Vec::new();

        // HTML-only build (no outcss/outjs): just the expanded markup, streamed.
        build(
            BuildOptions {
                input: vec![abs(&entry)],
                source: None,
                outcss: None,
                outjs: None,
                cwd: Some(cwd.clone()),
                minify: false,
            },
            &mut |chunk: &[u8]| {
                if !chunk.is_empty() {
                    html.extend_from_slice(chunk);
                }
            },
        );

        let html_file = format!("{id}.html");
        let html_path = out.join(&html_file);
        fs::write(&html_path, &html).unwrap();
        page_outputs.push((const_name, html_file, html_path));
    }

    run_shiki(
        &manifest,
        page_outputs.iter().map(|(_, _, path)| path.as_path()),
    );

    for (const_name, html_file, html_path) in page_outputs {
        let html = fs::read(&html_path).unwrap();
        let lens = chunk_lengths(&html)
            .iter()
            .map(usize::to_string)
            .collect::<Vec<_>>()
            .join(", ");
        generated.push_str(&format!(
            "pub static {const_name}: Page = Page {{ html: include_bytes!({html_file:?}), chunks: &[{lens}] }};\n"
        ));
    }

    generated.push('\n');
    generated.push_str("pub static STYLES_CSS: &str = include_str!(\"styles.css\");\n");
    generated.push_str("pub static SCRIPTS_JS: &str = include_str!(\"scripts.js\");\n");

    fs::write(out.join("generated.rs"), generated).unwrap();
}

fn run_shiki<'a>(manifest: &Path, files: impl IntoIterator<Item = &'a Path>) {
    let files = files.into_iter().collect::<Vec<_>>();
    if files.is_empty() {
        return;
    }

    let mut command = Command::new("node");
    command.current_dir(manifest).arg("scripts/highlight.mjs");
    for file in files {
        command.arg(file);
    }

    let output = command.output().expect("node should run Shiki highlighter");
    if !output.status.success() {
        panic!(
            "Shiki highlighting failed:\n{}\n{}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr),
        );
    }
}

fn chunk_lengths(html: &[u8]) -> Vec<usize> {
    const STREAM_CHUNK_SIZE: usize = 16 * 1024;
    if html.is_empty() {
        return Vec::new();
    }
    html.chunks(STREAM_CHUNK_SIZE)
        .map(|chunk| chunk.len())
        .collect()
}

/// Absolute path as a `String`, so wesc resolves it independently of `cwd`.
fn abs(path: &Path) -> String {
    path.to_string_lossy().into_owned()
}
