//! Build-time prep for the runtime-rendered site.
//!
//! The Worker renders HTML by running wesc *at request time* (wesc targets
//! `wasm32-unknown-unknown` for HTML expansion and CSS bundling), so this build
//! script no longer pre-expands pages. It does only the work that can't happen
//! inside the Worker:
//!
//! 1. Bundles the shared `scripts.js` with rolldown. JS bundling is native-only
//!    (rolldown doesn't target wasm), so it runs here, on the host, with wesc as
//!    a build dependency.
//! 2. Runs Shiki over the page *sources* to syntax-highlight their static code
//!    blocks (Shiki is a Node tool, also unavailable inside the Worker).
//! 3. Embeds the (highlighted) page sources, the component sources, and the
//!    `scripts.js` bundle into a small generated module (`generated.rs`) that
//!    `src/lib.rs` includes. At runtime the Worker feeds those sources to
//!    `wesc::build` as an in-memory `source` map and expands the HTML per
//!    request.

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use wesc::{build, BuildOptions};

/// Page sources that get Shiki highlighting before they're embedded. Everything
/// else under `web/` is embedded verbatim.
const PAGES: &[&str] = &["home.html", "docs.html", "not-found.html"];

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let web = manifest.join("web");
    let out = PathBuf::from(std::env::var("OUT_DIR").unwrap());

    // Rebuild whenever any component/page source — or the highlighter — changes.
    println!("cargo:rerun-if-changed={}", web.display());
    println!(
        "cargo:rerun-if-changed={}",
        manifest.join("scripts/highlight.ts").display()
    );

    // 1. Bundle the shared JS with rolldown (native-only). wesc runs from
    //    OUT_DIR so its `.wesc` scratch tree and the emitted bundle land there;
    //    the entry is absolute, so the source tree is untouched. The expanded
    //    HTML from this asset-only entry is discarded.
    let cwd = out.to_string_lossy().into_owned();
    build(
        BuildOptions {
            input: vec![abs(&web.join("assets.html"))],
            outjs: Some("scripts.js".to_string()),
            cwd: Some(cwd),
            minify: true,
            ..Default::default()
        },
        &mut |_chunk: &[u8]| {},
    );

    // 2. Mirror the source tree into OUT_DIR, highlighting the pages. The
    //    components and the asset manifest are embedded verbatim; wesc expands
    //    them at runtime.
    let src = out.join("src");
    let mut embeds: Vec<(String, PathBuf)> = Vec::new();

    let assets_dst = src.join("assets.html");
    copy(&web.join("assets.html"), &assets_dst);
    embeds.push(("/web/assets.html".to_string(), assets_dst));

    for entry in fs::read_dir(web.join("components")).unwrap() {
        let path = entry.unwrap().path();
        if path.extension().and_then(|e| e.to_str()) != Some("html") {
            continue;
        }
        let name = path.file_name().unwrap().to_string_lossy().into_owned();
        let dst = src.join("components").join(&name);
        copy(&path, &dst);
        embeds.push((format!("/web/components/{name}"), dst));
    }

    let mut page_dsts: Vec<PathBuf> = Vec::new();
    for name in PAGES {
        let dst = src.join("pages").join(name);
        copy(&web.join("pages").join(name), &dst);
        page_dsts.push(dst.clone());
        embeds.push((format!("/web/pages/{name}"), dst));
    }

    // 3. Shiki-highlight the (copied) page sources in place.
    run_shiki(&manifest, page_dsts.iter().map(PathBuf::as_path));

    // 4. Stitch it all into `generated.rs`: the JS bundle plus a function that
    //    rebuilds the in-memory source map the Worker feeds to `wesc::build`.
    let mut generated = String::new();
    generated.push_str("// @generated by build.rs — do not edit.\n\n");
    generated.push_str("/// The rolldown-bundled component JS, served from `/scripts.js`.\n");
    generated.push_str("pub static SCRIPTS_JS: &str = include_str!(\"scripts.js\");\n\n");
    generated.push_str(
        "/// The site sources (highlighted pages + components), keyed by the\n\
         /// absolute path the Worker uses as wesc's in-memory `source` map.\n\
         pub fn source_files() -> [(&'static str, &'static [u8]); ",
    );
    generated.push_str(&embeds.len().to_string());
    generated.push_str("] {\n    [\n");
    for (key, path) in &embeds {
        let include = path.strip_prefix(&out).unwrap();
        generated.push_str(&format!(
            "        ({key:?}, include_bytes!({:?})),\n",
            include.to_string_lossy()
        ));
    }
    generated.push_str("    ]\n}\n");

    fs::write(out.join("generated.rs"), generated).unwrap();
}

/// Copy `from` to `to`, creating parent directories as needed.
fn copy(from: &Path, to: &Path) {
    fs::create_dir_all(to.parent().unwrap()).unwrap();
    fs::copy(from, to).unwrap();
}

fn run_shiki<'a>(manifest: &Path, files: impl IntoIterator<Item = &'a Path>) {
    // Node runs the TypeScript highlighter directly via type stripping; the
    // `--disable-warning` flag silences the experimental-feature notice.
    let mut command = Command::new("node");
    command
        .current_dir(manifest)
        .arg("--disable-warning=ExperimentalWarning")
        .arg("scripts/highlight.ts");
    for file in files {
        command.arg(file);
    }

    let output = command.output().expect("node should run Shiki highlighter");
    if !output.status.success() {
        panic!(
            "Shiki highlighting failed:\n{}\n{}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr),
        );
    }
}

/// Absolute path as a `String`, so wesc resolves it independently of `cwd`.
fn abs(path: &Path) -> String {
    path.to_string_lossy().into_owned()
}
