//! WeSC marketing/docs site, served from a Cloudflare Worker.
//!
//! This is the dogfooding: the Worker runs **wesc itself at request time**.
//! wesc targets `wasm32-unknown-unknown` for HTML expansion and CSS bundling,
//! so the single-file `.html` components in `web/` are embedded into the Wasm
//! binary (see `build.rs`) and expanded per request straight inside the Worker —
//! no pre-rendered HTML.
//!
//! Only the parts wesc can't do on wasm happen at build time: the rolldown
//! `scripts.js` bundle (JS bundling is native-only) and Shiki highlighting of
//! the page code blocks. Everything else — expanding each page to HTML and
//! bundling the component CSS — runs here.
//!
//! HTML is **streamed** chunk by chunk so the browser can start rendering
//! before the whole body arrives. The CSS bundle (built once, then cached) and
//! the pre-bundled JS are served from their own long-lived, cacheable routes.

use std::collections::HashMap;
use std::sync::OnceLock;

use futures_util::stream;
use wesc::{build, BuildOptions};
use worker::*;

/// Generated by `build.rs`: `SCRIPTS_JS` plus `source_files()`, the embedded
/// (highlighted) page + component sources the Worker feeds to wesc.
mod generated {
    include!(concat!(env!("OUT_DIR"), "/generated.rs"));
}

/// HTML is streamed to the client in chunks of this size.
const STREAM_CHUNK_SIZE: usize = 16 * 1024;

/// The Worker's `fetch` entrypoint, invoked for every incoming HTTP request.
#[event(fetch)]
async fn fetch(req: Request, _env: Env, _ctx: Context) -> Result<Response> {
    // Surface Rust panics as `console.error` so they show up in `wrangler tail`.
    console_error_panic_hook::set_once();

    // This is a read-only site: only GET/HEAD are served.
    match req.method() {
        Method::Get | Method::Head => route(&req.path()),
        _ => Response::error("Method Not Allowed", 405),
    }
}

/// Resolve a request path to a response.
///
/// Trailing slashes are normalized so `/docs/` and `/docs` are equivalent.
/// Anything unrecognized falls through to a 404 that echoes the requested path.
fn route(path: &str) -> Result<Response> {
    // Normalize: drop a trailing slash, but keep "/" itself.
    let normalized = match path.trim_end_matches('/') {
        "" => "/",
        other => other,
    };

    match normalized {
        "/" => stream_page(render("/web/pages/home.html"), 200),
        "/docs" => stream_page(render("/web/pages/docs.html"), 200),
        "/styles.css" => serve_asset(styles_css().as_bytes(), "text/css; charset=utf-8"),
        "/scripts.js" => serve_asset(
            generated::SCRIPTS_JS.as_bytes(),
            "text/javascript; charset=utf-8",
        ),
        _ => stream_not_found(path),
    }
}

/// The in-memory `source` map wesc reads inputs from: every embedded page and
/// component, keyed by its absolute path (matching the `<link rel="definition">`
/// hrefs once resolved).
fn source_map() -> HashMap<String, Vec<u8>> {
    generated::source_files()
        .iter()
        .map(|&(path, bytes)| (path.to_string(), bytes.to_vec()))
        .collect()
}

/// Expand a page to HTML at request time. No `outcss`/`outjs`: just the
/// (lean) expanded markup. wesc reads every input from the in-memory `source`,
/// so the build never touches a filesystem — exactly what a Worker needs.
fn render(entry: &str) -> Vec<u8> {
    let mut html = Vec::new();
    build(
        BuildOptions {
            input: vec![entry.to_string()],
            source: Some(source_map()),
            ..Default::default()
        },
        &mut |chunk: &[u8]| html.extend_from_slice(chunk),
    );
    html
}

/// The bundled component CSS, built once with wesc (CSS bundling runs on wasm)
/// and cached for the lifetime of the Worker instance: it's identical for every
/// request. `outcss: Some("")` keeps it in memory only (no filesystem write).
fn styles_css() -> &'static str {
    static CSS: OnceLock<String> = OnceLock::new();
    CSS.get_or_init(|| {
        let assets = build(
            BuildOptions {
                input: vec!["/web/assets.html".to_string()],
                source: Some(source_map()),
                outcss: Some(String::new()),
                minify: true,
                ..Default::default()
            },
            &mut |_chunk: &[u8]| {},
        );
        assets.css.unwrap_or_default()
    })
}

/// Stream a page's HTML in bounded chunks.
fn stream_page(html: Vec<u8>, status: u16) -> Result<Response> {
    let chunks: Vec<std::result::Result<Vec<u8>, Error>> = html
        .chunks(STREAM_CHUNK_SIZE)
        .map(|chunk| Ok(chunk.to_vec()))
        .collect();

    let mut res = Response::from_stream(stream::iter(chunks))?.with_status(status);
    let headers = res.headers_mut();
    headers.set("Content-Type", "text/html; charset=utf-8")?;
    if status == 200 {
        headers.set("Cache-Control", "public, max-age=300")?;
    }
    Ok(res)
}

/// Render and stream the 404 page, substituting the requested path into its
/// placeholder.
fn stream_not_found(path: &str) -> Result<Response> {
    let body = String::from_utf8_lossy(&render("/web/pages/not-found.html"))
        .replace("{{PATH}}", &escape_html(path))
        .into_bytes();
    stream_page(body, 404)
}

/// Serve a cacheable asset bundle (CSS/JS). These are content-built and never
/// change between deploys, so they're cached aggressively.
fn serve_asset(body: &[u8], content_type: &str) -> Result<Response> {
    let mut res = Response::from_bytes(body.to_vec())?;
    let headers = res.headers_mut();
    headers.set("Content-Type", content_type)?;
    headers.set("Cache-Control", "public, max-age=31536000, immutable")?;
    Ok(res)
}

/// Minimal HTML-escaping for the untrusted request path interpolated into 404s.
fn escape_html(input: &str) -> String {
    input
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}
