//! WeSC marketing/docs site, served from a Cloudflare Worker.
//!
//! The pages, styles, and scripts are produced at build time by wesc itself
//! (see `build.rs`) — this is the dogfooding: single-file `.html` components in
//! `web/` are bundled into expanded HTML plus shared `styles.css` / `scripts.js`,
//! with code snippets highlighted by Shiki at build time.
//!
//! At request time the Worker just routes and serves those artifacts. HTML is
//! **streamed** chunk by chunk, so the browser can start rendering before the
//! whole body arrives.
//! The CSS and JS bundles are served from their own long-lived, cacheable
//! routes.

use futures_util::stream;
use worker::*;

/// Generated by `build.rs`: `Page` plus the `HOME`/`DOCS`/… page statics and
/// the `STYLES_CSS` / `SCRIPTS_JS` bundles.
mod generated {
    include!(concat!(env!("OUT_DIR"), "/generated.rs"));
}

/// The Worker's `fetch` entrypoint, invoked for every incoming HTTP request.
#[event(fetch)]
async fn fetch(req: Request, _env: Env, _ctx: Context) -> Result<Response> {
    // Surface Rust panics as `console.error` so they show up in `wrangler tail`.
    console_error_panic_hook::set_once();

    // This is a read-only site: only GET/HEAD are served.
    match req.method() {
        Method::Get | Method::Head => route(&req.path()),
        _ => Response::error("Method Not Allowed", 405),
    }
}

/// Resolve a request path to a response.
///
/// Trailing slashes are normalized so `/docs/` and `/docs` are equivalent.
/// Anything unrecognized falls through to a streamed 404 that echoes the
/// requested path.
fn route(path: &str) -> Result<Response> {
    // Normalize: drop a trailing slash, but keep "/" itself.
    let normalized = match path.trim_end_matches('/') {
        "" => "/",
        other => other,
    };

    match normalized {
        "/" => stream_page(&generated::HOME, 200),
        "/docs" => stream_page(&generated::DOCS, 200),
        "/styles.css" => serve_asset(generated::STYLES_CSS.as_bytes(), "text/css; charset=utf-8"),
        "/scripts.js" => serve_asset(
            generated::SCRIPTS_JS.as_bytes(),
            "text/javascript; charset=utf-8",
        ),
        _ => stream_not_found(path),
    }
}

/// Stream a pre-built page in bounded chunks.
fn stream_page(page: &'static generated::Page, status: u16) -> Result<Response> {
    let mut offset = 0usize;
    let mut chunks: Vec<std::result::Result<Vec<u8>, Error>> =
        Vec::with_capacity(page.chunks.len());
    for &len in page.chunks {
        let end = offset + len;
        chunks.push(Ok(page.html[offset..end].to_vec()));
        offset = end;
    }

    let mut res = Response::from_stream(stream::iter(chunks))?.with_status(status);
    let headers = res.headers_mut();
    headers.set("Content-Type", "text/html; charset=utf-8")?;
    if status == 200 {
        headers.set("Cache-Control", "public, max-age=300")?;
    }
    Ok(res)
}

/// Stream the 404 page, substituting the requested path into its placeholder.
fn stream_not_found(path: &str) -> Result<Response> {
    let body = String::from_utf8_lossy(generated::NOT_FOUND.html)
        .replace("{{PATH}}", &escape_html(path))
        .into_bytes();

    let chunk = vec![Ok::<_, Error>(body)];
    let mut res = Response::from_stream(stream::iter(chunk))?.with_status(404);
    res.headers_mut()
        .set("Content-Type", "text/html; charset=utf-8")?;
    Ok(res)
}

/// Serve a build-time asset bundle (CSS/JS). These are content-built and never
/// change between deploys, so they're cached aggressively.
fn serve_asset(body: &[u8], content_type: &str) -> Result<Response> {
    let mut res = Response::from_bytes(body.to_vec())?;
    let headers = res.headers_mut();
    headers.set("Content-Type", content_type)?;
    headers.set("Cache-Control", "public, max-age=31536000, immutable")?;
    Ok(res)
}

/// Minimal HTML-escaping for the untrusted request path interpolated into 404s.
fn escape_html(input: &str) -> String {
    input
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}
